<?php
/**
 * @file
 * Code for the luggage_aliases feature.
 */

include_once 'luggage_aliases.features.inc';
include_once 'luggage_aliases.views_default.inc';

const LUGGAGE_ALIASES_VOCAB_NAME = 'aliases';

/**
 * Implements hook_FORM_ID_form_alter()
 */
function luggage_aliases_form_people_node_form_alter(&$form, &$form_state, $form_id) {
  // hide the aliases field from users.
  // TODO: Wrap this around permissions to expose it to people who can edit aliases.
  $form['field_people_aliases']['#access'] = false;
}

/**
 * Implments hook_node_presave()
 */
function luggage_aliases_node_presave($node) {

  if ($node->type == 'people') {
    // Generate alias term when adding or updating a people node.
    $new_name = luggage_aliases_generate_term_name($node);
    $old_name = '';
    if (!$node->is_new) {
      $old_name = luggage_aliases_generate_term_name($node->original);
    }

    if (empty($node->field_people_aliases)) {
      // Create the term if none exist.
      $tid = luggage_aliases_create_term($new_name);

      // add the term to the list of aliases in this node.
      $term = taxonomy_term_load($tid);
      $node->field_people_aliases['und'][] = (array) $term; // casting $term from object to array because it's expected later in node_save().
    }
    else if ($new_name != $old_name) {
      // Otherwise update the term if the name has changed.
      $term = taxonomy_term_load($node->field_people_aliases['und'][0]['tid']);
      $term->name = $new_name;

      taxonomy_term_save($term);
    }
  }
}

/**
 * Generate a term name based on the data provided in the node.
 * @param $node - Node object
 * @return - The formatted term name to be used when creating an alias term.
 */
function luggage_aliases_generate_term_name($node) {
  // We're using the node's title and cleaning out the extra whitespaces.
  return preg_replace('/\s+/', ' ', $node->title);
}

/**
 * Creates a taxonomy term with the people profiles nid it is related to.
 * @param $name - The name of the term to be saved.
 * @param $nid - The nid of the people profile creating the term.
 * @return - tid of the created term.
 */
function luggage_aliases_create_term($name) {

  $term = new stdClass();
  $term->vid = luggage_aliases_get_vocabulary_id(LUGGAGE_ALIASES_VOCAB_NAME);
  $term->name = $name;

  taxonomy_term_save($term);

  return $term->tid;
}

/**
 * @param $name - machine name of the vocabulary
 * @return false or the vid for the named vocabulary
 */
function luggage_aliases_get_vocabulary_id($name) {
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  if ($vocabulary) {
    return $vocabulary->vid;
  }

  return FALSE;
}







/**
 * Implements hook_field_formatter_info()
 */
function luggage_aliases_field_formatter_info() {
  $info = array(
    'author_list' => array(
      'label' => t('Author List'),
      'field types' => array('taxonomy_term_reference'),
      'description' => t('Displays Title as a link and URL as plain text.'),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_view()
 */
function luggage_aliases_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'author_list':
      foreach ($items as $delta => $item) {
        $query = db_select('taxonomy_index','t')->fields('t');
        $query->condition('t.tid',$item['tid'],'=');
        $nodes = db_select('node','n')->fields('n')->condition('type','people');
        $d = $query->join($nodes,'n','t.nid = n.nid');
        $data = $query->execute()->fetchCol();
        if($data) {
          $user = node_load($data[0]);
          $element[$delta] = array(
            '#theme' => 'luggage_aliases_default',
            '#image_src' => image_style_url('thumbnail',$user->field_people_image[LANGUAGE_NONE][0]['uri']),
            '#firstname' => $user->field_people_first_name[LANGUAGE_NONE][0]['value'],
            '#lastname' => $user->field_people_last_name[LANGUAGE_NONE][0]['value'],
            '#position' => $user->field_people_position[LANGUAGE_NONE][0]['value'],
            '#url' => $user->nid,
            '#bio' => (isset($user->field_people_bio[LANGUAGE_NONE][0]['value']))?substr($user->field_people_bio[LANGUAGE_NONE][0]['value'],0,300) . '...':'',
          );
        } else {
          $term = taxonomy_term_load($item['tid']);
          if($term) {
            $element[$delta] = array(
              '#theme' => 'luggage_aliases_default',
              '#aliasName' => $term->name,
              '#url' => '/authors/' . $term->tid,
            );
          }
        }
      }
      drupal_add_css(drupal_get_path('module', 'luggage_aliases') . '/css/luggage_aliases.css');
      break;
  }
  return $element;
}

/**
 * Implements hook_theme()
 */
function luggage_aliases_theme() {
  return array(
    'luggage_aliases_default' => array(
      'template' => 'luggage_aliases_default',
      'variables' => array(
        'image_src' => Null,
        'firstname' => Null,
        'lastname' => Null,
        'position' => Null,
        'url' => Null,
        'bio' => Null,
        'aliasName' => Null,
      ),
      'path' => drupal_get_path('module','luggage_aliases') . '/templates'
    )
  );
}

/**
 * Implements hook_views_pre_view()
 */
function luggage_aliases_views_pre_view(&$view, &$display_id, &$args) {
  // Grab the views config provided by features which is needed to check the
  // display id
  $views = luggage_aliases_views_default_views();
  // Confirm that this is the right view
  if(isset($views[$view->name]) && isset($views[$view->name]->display[$display_id]) && arg(0) == 'node') {
    // Get the author's aliases
    $node = node_load(arg(1));
    // Build up the contextual filter array
    foreach($node->field_people_aliases[LANGUAGE_NONE] as $value) {
      $args[] = $value['tid'];
    }
  }
}
